[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/arch/riscv/riscv64-efi.ld",
    "-Clink-arg=-Map=/tmp/maia.map",
]

[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
